In [2]:
#Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
#load dataset

dataset = pd.read_csv('Churn_Modelling.csv')

In [5]:
dataset.head


<bound method NDFrame.head of       RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173       

In [6]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values


In [7]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [10]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [11]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [12]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [13]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

Using TensorFlow backend.


In [14]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [15]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [16]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [17]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [18]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 150)

Epoch 1/150
8000/8000 [==============================] - 4s 495us/step - loss: 0.4782 - acc: 0.7960
Epoch 2/150
8000/8000 [==============================] - 3s 353us/step - loss: 0.4266 - acc: 0.7960
Epoch 3/150
8000/8000 [==============================] - 3s 324us/step - loss: 0.4204 - acc: 0.8050
Epoch 4/150
8000/8000 [==============================] - 3s 337us/step - loss: 0.4174 - acc: 0.8236
Epoch 5/150
8000/8000 [==============================] - 2s 303us/step - loss: 0.4160 - acc: 0.8285
Epoch 6/150
8000/8000 [==============================] - 3s 379us/step - loss: 0.4142 - acc: 0.8302
Epoch 7/150
8000/8000 [==============================] - 3s 333us/step - loss: 0.4127 - acc: 0.8330
Epoch 8/150
8000/8000 [==============================] - 3s 316us/step - loss: 0.4117 - acc: 0.8320
Epoch 9/150
8000/8000 [==============================] - 3s 334us/step - loss: 0.4110 - acc: 0.8340
Epoch 10/150
8000/8000 [==============================] - 2s 312us/step - loss: 0.4101 - acc: 0.8345

8000/8000 [==============================] - 2s 293us/step - loss: 0.3956 - acc: 0.8351
Epoch 81/150
8000/8000 [==============================] - 2s 291us/step - loss: 0.3959 - acc: 0.8350
Epoch 82/150
8000/8000 [==============================] - 2s 296us/step - loss: 0.3960 - acc: 0.8359
Epoch 83/150
8000/8000 [==============================] - 2s 292us/step - loss: 0.3956 - acc: 0.8360
Epoch 84/150
8000/8000 [==============================] - 2s 304us/step - loss: 0.3957 - acc: 0.8367
Epoch 85/150
8000/8000 [==============================] - 2s 296us/step - loss: 0.3959 - acc: 0.8356
Epoch 86/150
8000/8000 [==============================] - 2s 297us/step - loss: 0.3958 - acc: 0.8361
Epoch 87/150
8000/8000 [==============================] - 2s 297us/step - loss: 0.3956 - acc: 0.8351
Epoch 88/150
8000/8000 [==============================] - 2s 296us/step - loss: 0.3955 - acc: 0.8361
Epoch 89/150
8000/8000 [==============================] - 2s 298us/step - loss: 0.3955 - acc: 0.8352
Epo

In [19]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [22]:
cm

array([[1544,   51],
       [ 264,  141]], dtype=int64)

In [21]:
y_pred

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)